// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxabcbkyhlytnnqtqavc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YWJjYmt5aGx5dG5ucXRxYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDc1NTIsImV4cCI6MjA2MDIyMzU1Mn0.nJ2sIyOc9EnUEnT0kJmWK_Wz03ULPru9cDrHPyByb1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);